name: demcp_meson_mcp
description: "Meson MCP"
version: 1.0.0
model: stdio
env:
  - name: "env_name(require)"
    description: "env_des (require)"
    type: "string(require)"
    source_url: "get_env_source"
    require: true(require)
mcp_config:
  tools:
    - name: MESON_PRIVATE_KEY
      description: "The private key of the Meson account"
    - name: MESON_PUBLIC_KEY
      description: "The public key of the Meson account"
    - name: MESON_ADDRESS
      description: "The address of the Meson account"
start_config:
  command: "npx"
  args:
    - "deno"
    - "run"
    - "--allow-env"
    - "--allow-net"
    - "--allow-read"
    - "jsr:@demcp/meson-mcp"
